config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get '/home', to: 'pages#home'
  get '/d3', to: 'pages#d3'
  get '/challenges/try', to: 'pages#try_challenge'

  resources :users, except: [:new, :destroy]
  get '/register', to: 'users#new'
  
  resources :games do
    member do
      post 'like'
    end
  end

  resources :articles do
    resources :comments
  end
  
  get '/login', to: "logins#new"
  post '/login', to: "logins#create"
  get '/logout', to: "logins#destroy"
  
  resources :tags, only: [:new, :create, :show]
  

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <p>&copy; Front-End-Demo Patricio Jeri 2015</p>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
  <header class="navbar navbar-fixed-top navbar-default">
    <div class="container">
      <%= link_to "Demo", root_path, class: "btn btn-lg btn-success", id: "logo" %>
      <div class="nav_item"> <%= link_to "Blog", articles_path, class: "btn btn-default btn-warning" %> </div>
      <div class="nav_item"> <%= link_to "Recipes", games_path, class: "btn btn-default btn-warning" %> </div>
      <ul class="nav_ul_item">
        <li class="dropdown">
            <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
              Tags <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <% Tag.all.each do |tag| %>
                <li><%= link_to tag.name, tag_path(tag) %></li>
              <% end %>
              <% if logged_in? %>
                <li class="divider"></li>
                <li>
                  <%= link_to(new_tag_path) do %>
                  New Tag
                  <% end %>
                </li>
              <% end %>
            </ul>
          </li>
      </ul>
      <% if logged_in? %>  
        <div class="nav_item"> <%= link_to "New Recipe", new_game_path, class: "btn btn-default btn-warning" %> </div>
        <ul class="nav_item">
          <li class="dropdown">
            <%= link_to '#', class: "btn btn-default btn-danger dropdown-toggle", "data-toggle" => "dropdown" do %>
              <%= current_user.username %> <b class="caret"></b>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to "View Profile", user_path(current_user) %></li>
              <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Logout", logout_path %></li>
            </ul>
          </li>
        </ul>
      <% else %>
        <div class="nav_item"> <%= link_to "Log in", login_path, class: "btn btn-default btn-success" %> </div>
      <% end %>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Front End Demo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="container">
  <%= render 'layouts/messages' %>

  <%= yield %>

  <%= render '/layouts/footer' %>
</div>

</body>

</html>